baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = 'サンプルサイト'
defaultContentLanguage = "ja"

[taxonomies]
category = "categories"
course = "courses"

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true

[outputs]
home = ["HTML"]
section = ["HTML"]
page = ["HTML"]
